# Essential python for DA

## OOP

teach python to understand object
*   attribute : attribute of object
*   methods : function for object

In [ ]:
class Dog:
    #attribute
    def __init__(self,name,species,age):
        self.name=name
        self.species=species
        self.age=age

    #function
    def bark(self):
        print(f"{self.name} is hong hong")

    def hbd(self):
        self.age+=1
        print(f"{self.name} is now {self.age} years old")

In [ ]:
dog1=Dog("milo","siberian husky",2)
dog2=Dog("david","Shiba",3)

In [ ]:
print(f"{dog1.name} is {dog1.species}")

milo is siberian husky

In [ ]:
dog2.bark()

david is hong hong

In [ ]:
dog1.hbd()

milo is now 3 years old

OOP-Super class

class that extend from other class

In [2]:
class Person:
    def __init__ (self,name,age):
        self.name=name
        self.age=age

#extension
class Employee(Person):
    def __init__(self, name, age,company):
        #refer to Super class
        super().__init__(name, age)
        self.company=company

    def greeting(self):
        print("hello world")

In [7]:
person1=Person("bright",23)

In [8]:
#person cant used employee func
person1.greeting()

AttributeError: 'Person' object has no attribute 'greeting'

In [5]:
person2=Employee("Lisa",37,"Black pink")

In [6]:
person2.greeting()

hello world

## Try-except block

In [9]:
#ZeroDivisionError
1/0

ZeroDivisionError: division by zero

In [12]:
try:
    result=1/0
except:
    print("this is error message : cant be division by 0")

this is error message : cant be division by 0

In [13]:
#magic command
!cat hotel.csv

hotel_id,name,city,star_rating,price_per_night
101,Grand Plaza,New York,5,350
102,Ocean View,Miami,4,220
103,Mountain Retreat,Denver,4,185
104,The Urban Stay,Chicago,3,140
105,Sunset Resort,Los Angeles,5,410
106,Desert Inn,Phoenix,3,95
107,Heritage House,Boston,4,210
108,Lakeside Lodge,Seattle,3,130
109,Golden Gate Suites,San Francisco,5,380
110,Central Boutique,Austin,4,195

In [14]:
#read file
import csv

In [19]:
#file not found error
try:
    file=open("hotel.csv","r") #r w a
    #csv.reader(csv_file)
    data =csv.reader(file)
    for row in data:
        print(row)
    #if not close -> oppunity to corrupt
    file.close()
except FileNotFoundError:
    print("file not found, please check filename again.")
# at the end
finally:
    print("read file succesfully")

['hotel_id', 'name', 'city', 'star_rating', 'price_per_night']
['101', 'Grand Plaza', 'New York', '5', '350']
['102', 'Ocean View', 'Miami', '4', '220']
['103', 'Mountain Retreat', 'Denver', '4', '185']
['104', 'The Urban Stay', 'Chicago', '3', '140']
['105', 'Sunset Resort', 'Los Angeles', '5', '410']
['106', 'Desert Inn', 'Phoenix', '3', '95']
['107', 'Heritage House', 'Boston', '4', '210']
['108', 'Lakeside Lodge', 'Seattle', '3', '130']
['109', 'Golden Gate Suites', 'San Francisco', '5', '380']
['110', 'Central Boutique', 'Austin', '4', '195']
read file succesfully

In [21]:
#context manager
with open("hotel.csv","r") as file:
    data= csv.reader(file)
    for row in data:
        print(row)

['hotel_id', 'name', 'city', 'star_rating', 'price_per_night']
['101', 'Grand Plaza', 'New York', '5', '350']
['102', 'Ocean View', 'Miami', '4', '220']
['103', 'Mountain Retreat', 'Denver', '4', '185']
['104', 'The Urban Stay', 'Chicago', '3', '140']
['105', 'Sunset Resort', 'Los Angeles', '5', '410']
['106', 'Desert Inn', 'Phoenix', '3', '95']
['107', 'Heritage House', 'Boston', '4', '210']
['108', 'Lakeside Lodge', 'Seattle', '3', '130']
['109', 'Golden Gate Suites', 'San Francisco', '5', '380']
['110', 'Central Boutique', 'Austin', '4', '195']

In [22]:
#context manager ver 2
read_data=[]
with open("hotel.csv","r") as file:
    data= csv.reader(file)
    for row in data:
        read_data.append(row)

In [24]:
#header
read_data[0]

['hotel_id', 'name', 'city', 'star_rating', 'price_per_night']

In [26]:
data_count=len(read_data)

In [34]:
#for loop to calculate avg,price per night
price=[]
for row in read_data[1:]:
    price.append(int(row[-1]))

avg_price_per_night=sum(price)/data_count
print(f"average price per night is {avg_price_per_night}")

average price per night is 210.45454545454547

In [36]:
price=0
for row in read_data[1:]:
    price += (int(row[-1]))

avg_price_per_night=price/data_count
print(f"average price per night is {avg_price_per_night}")

average price per night is 210.45454545454547

In [37]:
#modern python
import pandas as pd
df= pd.read_csv("hotel.csv")

In [38]:
df['price_per_night'].mean()

np.float64(231.5)

## Read & write file

In [39]:
import csv

In [40]:
#write file + context manager
head=["id","name","city"]
body=[
    [1,"CU","Bangkok"],
    [2,"MU","Nakhon pathom"],
    [3,"TU","Pathum thani"]
]
with open("school.csv","w") as file :
    writer = csv.writer(file)
    #write one line
    writer.writerow(head)
    #write multiple line
    writer.writerows(body)

In [41]:
!cat school.csv

id,name,city
1,CU,Bangkok
2,MU,Nakhon pathom
3,TU,Pathum thani

In [42]:
df=pd.read_csv("school.csv")
df

   id name           city
0   1   CU        Bangkok
1   2   MU  Nakhon pathom
2   3   TU   Pathum thani

In [43]:
#export file in pandas
df.to_csv("school2.csv")

In [48]:
#read data from internet
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv"

In [49]:
df_penguine=pd.read_csv(url)
df_penguine

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [50]:
#select column
df_penguine[['species','island','bill_length_mm']].head(10)

  species     island  bill_length_mm
0  Adelie  Torgersen            39.1
1  Adelie  Torgersen            39.5
2  Adelie  Torgersen            40.3
3  Adelie  Torgersen             NaN
4  Adelie  Torgersen            36.7
5  Adelie  Torgersen            39.3
6  Adelie  Torgersen            38.9
7  Adelie  Torgersen            39.2
8  Adelie  Torgersen            34.1
9  Adelie  Torgersen            42.0

In [53]:
df_penguine.query("island == 'Torgersen' and species=='Adelie' ")

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,MALE
6,Adelie,Torgersen,38.9,17.8,181.0,3625.0,FEMALE
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,MALE
8,Adelie,Torgersen,34.1,18.1,193.0,3475.0,NaN
9,Adelie,Torgersen,42.0,20.2,190.0,4250.0,NaN
10,Adelie,Torgersen,37.8,17.1,186.0,3300.0,NaN
11,Adelie,Torgersen,37.8,17.3,180.0,3700.0,NaN
12,Adelie,Torgersen,41.1,17.6,182.0,3200.0,FEMALE
13,Adelie,Torgersen,38.6,21.2,191.0,3800.0,MALE
14,Adelie,Torgersen,34.6,21.1,198.0,4400.0,MALE
15,Adelie,Torgersen,36.6,17.8,185.0,3700.0,FEMALE
16,Adelie,Torgersen,38.7,19.0,195.0,3450.0,FEMALE
17,Adelie,Torgersen,42.5,20.7,197.0,4500.0,MALE
18,Adelie,Torgersen,34.4,18.4,184.0,3325.0,FEMALE
19,Adelie,Torgersen,46.0,21.5,194.0,4200.0,MALE
68,Adelie,Torgersen,35.9,16.6,190.0,3050.0,FEMALE
69,Adelie,Torgersen,41.8,19.4,198.0,4450.0,MALE
70,Adelie,Torgersen,33.5,19.0,190.0,3600.0,FEMALE
71,Adelie,Torgersen,39.7,18.4,190.0,3900.0,MALE
72,Adelie,Torgersen,39.6,17.2,196.0,3550.0,FEMALE
73,Adelie,Torgersen,45.8,18.9,197.0,4150.0,MALE
74,Adelie,Torgersen,35.5,17.5,190.0,3700.0,FEMALE
75,Adelie,Torgersen,42.8,18.5,195.0,4250.0,MALE
76,Adelie,Torgersen,40.9,16.8,191.0,3700.0,FEMALE
77,Adelie,Torgersen,37.2,19.4,184.0,3900.0,MALE
78,Adelie,Torgersen,36.2,16.1,187.0,3550.0,FEMALE
79,Adelie,Torgersen,42.1,19.1,195.0,4000.0,MALE
80,Adelie,Torgersen,34.6,17.2,189.0,3200.0,FEMALE
81,Adelie,Torgersen,42.9,17.6,196.0,4700.0,MALE
82,Adelie,Torgersen,36.7,18.8,187.0,3800.0,FEMALE
83,Adelie,Torgersen,35.1,19.4,193.0,4200.0,MALE
116,Adelie,Torgersen,38.6,17.0,188.0,2900.0,FEMALE
117,Adelie,Torgersen,37.3,20.5,199.0,3775.0,MALE
118,Adelie,Torgersen,35.7,17.0,189.0,3350.0,FEMALE
119,Adelie,Torgersen,41.1,18.6,189.0,3325.0,MALE
120,Adelie,Torgersen,36.2,17.2,187.0,3150.0,FEMALE
121,Adelie,Torgersen,37.7,19.8,198.0,3500.0,MALE
122,Adelie,Torgersen,40.2,17.0,176.0,3450.0,FEMALE
123,Adelie,Torgersen,41.4,18.5,202.0,3875.0,MALE
124,Adelie,Torgersen,35.2,15.9,186.0,3050.0,FEMALE
125,Adelie,Torgersen,40.6,19.0,199.0,4000.0,MALE
126,Adelie,Torgersen,38.8,17.6,191.0,3275.0,FEMALE
127,Adelie,Torgersen,41.5,18.3,195.0,4300.0,MALE
128,Adelie,Torgersen,39.0,17.1,191.0,3050.0,FEMALE
129,Adelie,Torgersen,44.1,18.0,210.0,4000.0,MALE
130,Adelie,Torgersen,38.5,17.9,190.0,3325.0,FEMALE
131,Adelie,Torgersen,43.1,19.2,197.0,3500.0,MALE

In [52]:
##filter row
df_penguine[['species','island','bill_length_mm']].query("island == 'Torgersen' and species=='Adelie' ")

    species     island  bill_length_mm
0    Adelie  Torgersen            39.1
1    Adelie  Torgersen            39.5
2    Adelie  Torgersen            40.3
3    Adelie  Torgersen             NaN
4    Adelie  Torgersen            36.7
5    Adelie  Torgersen            39.3
6    Adelie  Torgersen            38.9
7    Adelie  Torgersen            39.2
8    Adelie  Torgersen            34.1
9    Adelie  Torgersen            42.0
10   Adelie  Torgersen            37.8
11   Adelie  Torgersen            37.8
12   Adelie  Torgersen            41.1
13   Adelie  Torgersen            38.6
14   Adelie  Torgersen            34.6
15   Adelie  Torgersen            36.6
16   Adelie  Torgersen            38.7
17   Adelie  Torgersen            42.5
18   Adelie  Torgersen            34.4
19   Adelie  Torgersen            46.0
68   Adelie  Torgersen            35.9
69   Adelie  Torgersen            41.8
70   Adelie  Torgersen            33.5
71   Adelie  Torgersen            39.7
72   Adelie  Torgersen            39.6
73   Adelie  Torgersen            45.8
74   Adelie  Torgersen            35.5
75   Adelie  Torgersen            42.8
76   Adelie  Torgersen            40.9
77   Adelie  Torgersen            37.2
78   Adelie  Torgersen            36.2
79   Adelie  Torgersen            42.1
80   Adelie  Torgersen            34.6
81   Adelie  Torgersen            42.9
82   Adelie  Torgersen            36.7
83   Adelie  Torgersen            35.1
116  Adelie  Torgersen            38.6
117  Adelie  Torgersen            37.3
118  Adelie  Torgersen            35.7
119  Adelie  Torgersen            41.1
120  Adelie  Torgersen            36.2
121  Adelie  Torgersen            37.7
122  Adelie  Torgersen            40.2
123  Adelie  Torgersen            41.4
124  Adelie  Torgersen            35.2
125  Adelie  Torgersen            40.6
126  Adelie  Torgersen            38.8
127  Adelie  Torgersen            41.5
128  Adelie  Torgersen            39.0
129  Adelie  Torgersen            44.1
130  Adelie  Torgersen            38.5
131  Adelie  Torgersen            43.1

In [54]:
#format split code into multiple libe
df_penguine[['species','island','bill_length_mm']] \
.query("island == 'Torgersen' and species=='Adelie' ") \
.head(10)

  species     island  bill_length_mm
0  Adelie  Torgersen            39.1
1  Adelie  Torgersen            39.5
2  Adelie  Torgersen            40.3
3  Adelie  Torgersen             NaN
4  Adelie  Torgersen            36.7
5  Adelie  Torgersen            39.3
6  Adelie  Torgersen            38.9
7  Adelie  Torgersen            39.2
8  Adelie  Torgersen            34.1
9  Adelie  Torgersen            42.0

R vs python


*   df  %>%
         select() %>%
         filter()
*   df.select().filter() or
*   df \
    .select()\
    .filter()

In [55]:
#filter without query
df_penguine[df_penguine['body_mass_g']>=4500][['species','island','bill_length_mm']]

    species     island  bill_length_mm
7    Adelie  Torgersen            39.2
17   Adelie  Torgersen            42.5
39   Adelie      Dream            39.8
45   Adelie      Dream            39.6
81   Adelie  Torgersen            42.9
..      ...        ...             ...
338  Gentoo     Biscoe            47.2
340  Gentoo     Biscoe            46.8
341  Gentoo     Biscoe            50.4
342  Gentoo     Biscoe            45.2
343  Gentoo     Biscoe            49.9

[118 rows x 3 columns]

## Request API

In [16]:
import requests
import pandas as pd

#API endpoint
url="https://swapi.info/api/people"

In [9]:
response = requests.get(url)

In [13]:
response_json=response.json()
response_json

[{'name': 'Luke Skywalker',
  'height': '172',
  'mass': '77',
  'hair_color': 'blond',
  'skin_color': 'fair',
  'eye_color': 'blue',
  'birth_year': '19BBY',
  'gender': 'male',
  'homeworld': 'https://swapi.info/api/planets/1',
  'films': ['https://swapi.info/api/films/1',
   'https://swapi.info/api/films/2',
   'https://swapi.info/api/films/3',
   'https://swapi.info/api/films/6'],
  'species': [],
  'vehicles': ['https://swapi.info/api/vehicles/14',
   'https://swapi.info/api/vehicles/30'],
  'starships': ['https://swapi.info/api/starships/12',
   'https://swapi.info/api/starships/22'],
  'created': '2014-12-09T13:50:51.644000Z',
  'edited': '2014-12-20T21:17:56.891000Z',
  'url': 'https://swapi.info/api/people/1'},
 {'name': 'C-3PO',
  'height': '167',
  'mass': '75',
  'hair_color': 'n/a',
  'skin_color': 'gold',
  'eye_color': 'yellow',
  'birth_year': '112BBY',
  'gender': 'n/a',
  'homeworld': 'https://swapi.info/api/planets/1',
  'films': ['https://swapi.info/api/films/1',
   'https://swapi.info/api/films/2',
   'https://swapi.info/api/films/3',
   'https://swapi.info/api/films/4',
   'https://swapi.info/api/films/5',
   'https://swapi.info/api/films/6'],
  'species': ['https://swapi.info/api/species/2'],
  'vehicles': [],
  'starships': [],
  'created': '2014-12-10T15:10:51.357000Z',
  'edited': '2014-12-20T21:17:50.309000Z',
  'url': 'https://swapi.info/api/people/2'},
 {'name': 'R2-D2',
  'height': '96',
  'mass': '32',
  'hair_color': 'n/a',
  'skin_color': 'white, blue',
  'eye_color': 'red',
  'birth_year': '33BBY',
  'gender': 'n/a',
  'homeworld': 'https://swapi.info/api/planets/8',
  'films': ['https://swapi.info/api/films/1',
   'https://swapi.info/api/films/2',
   'https://swapi.info/api/films/3',
   'https://swapi.info/api/films/4',
   'https://swapi.info/api/films/5',
   'https://swapi.info/api/films/6'],
  'species': ['https://swapi.info/api/species/2'],
  'vehicles': [],
  'starships': [],
  'created': '2014-12-10T15:11:50.376000Z',
  'edited': '2014-12-20T21:17:50.311000Z',
  'url': 'https://swapi.info/api/people/3'},
 {'name': 'Darth Vader',
  'height': '202',
  'mass': '136',
  'hair_color': 'none',
  'skin_color': 'white',
  'eye_color': 'yellow',
  'birth_year': '41.9BBY',
  'gender': 'male',
  'homeworld': 'https://swapi.info/api/planets/1',
  'films': ['https://swapi.info/api/films/1',
   'https://swapi.info/api/films/2',
   'https://swapi.info/api/films/3',
   'https://swapi.info/api/films/6'],
  'species': [],
  'vehicles': [],
  'starships': ['https://swapi.info/api/starships/13'],
  'created': '2014-12-10T15:18:20.704000Z',
  'edited': '2014-12-20T21:17:50.313000Z',
  'url': 'https://swapi.info/api/people/4'},
 {'name': 'Leia Organa',
  'height': '150',
  'mass': '49',
  'hair_color': 'brown',
  'skin_color': 'light',
  'eye_color': 'brown',
  'birth_year': '19BBY',
  'gender': 'female',
  'homeworld': 'https://swapi.info/api/planets/2',
  'films': ['https://swapi.info/api/films/1',
   'https://swapi.info/api/films/2',
   'https://swapi.info/api/films/3',
   'https://swapi.info/api/films/6'],
  'species': [],
  'vehicles': ['https://swapi.info/api/vehicles/30'],
  'starships': [],
  'created': '2014-12-10T15:20:09.791000Z',
  'edited': '2014-12-20T21:17:50.315000Z',
  'url': 'https://swapi.info/api/people/5'},
 {'name': 'Owen Lars',
  'height': '178',
  'mass': '120',
  'hair_color': 'brown, grey',
  'skin_color': 'light',
  'eye_color': 'blue',
  'birth_year': '52BBY',
  'gender': 'male',
  'homeworld': 'https://swapi.info/api/planets/1',
  'films': ['https://swapi.info/api/films/1',
   'https://swapi.info/api/films/5',
   'https://swapi.info/api/films/6'],
  'species': [],
  'vehicles': [],
  'starships': [],
  'created': '2014-12-10T15:52:14.024000Z',
  'edited': '2014-12-20T21:17:50.317000Z',
  'url': 'https://swapi.info/api/people/6'},
 {'name': 'Beru Whitesun lars',
  'height': '165',
  'mass': '75',
  'hair_color': 'brown',
  'skin_color': 'light',
  'eye_color': 'blue',
  'birth_year': '47BBY',
  'gender': 'female',
  'homeworld': 'https://swapi.info/api/planets/1',
  'films': ['https://swapi.info/api/films/1',
   'https://swapi.info/api/films/5',
   'https://swapi.info/api/films/6'],
  'species': [],
  'vehicles': [],
  'starships': [],
  'created': '2014-12-10T15:53:41.121000Z',
  'edited': '2014-12-20T21:17:50.319000Z',
  'url': 'https://swapi.info/api/people/7'},
 {'name': 'R5-D4',
  'height': '97',
  'mass': '32',
  'hair_color': 'n/a',
  'skin_color': 'white, red',
  'eye_color': 'red',
  'birth_year': 'unknown',
  'gender': 'n/a',
  'homeworld': 'https://swapi.info/api/planets/1',
  'films': ['https://swapi.info/api/films/1'],
  'species': ['https://swapi.info/api/species/2'],
  'vehicles': [],
  'starships': [],
  'created': '2014-12-10T15:57:50.959000Z',
  'edited': '2014-12-20T21:17:50.321000Z',
  'url': 'https://swapi.info/api/people/8'},
 {'name': 'Biggs Darklighter',
  'height': '183',
  'mass': '84',
  'hair_color': 'black',
  'skin_color': 'light',
  'eye_color': 'brown',
  'birth_year': '24BBY',
  'gender': 'male',
  'homeworld': 'https://swapi.info/api/planets/1',
  'films': ['https://swapi.info/api/films/1'],
  'species': [],
  'vehicles': [],
  'starships': ['https://swapi.info/api/starships/12'],
  'created': '2014-12-10T15:59:50.509000Z',
  'edited': '2014-12-20T21:17:50.323000Z',
  'url': 'https://swapi.info/api/people/9'},
 {'name': 'Obi-Wan Kenobi',
  'height': '182',
  'mass': '77',
  'hair_color': 'auburn, white',
  'skin_color': 'fair',
  'eye_color': 'blue-gray',
  'birth_year': '57BBY',
  'gender': 'male',
  'homeworld': 'https://swapi.info/api/planets/20',
  'films': ['https://swapi.info/api/films/1',
   'https://swapi.info/api/films/2',
   'https://swapi.info/api/films/3',
   'https://swapi.info/api/films/4',
   'https://swapi.info/api/films/5',
   'https://swapi.info/api/films/6'],
  'species': [],
  'vehicles': ['https://swapi.info/api/vehicles/38'],
  'starships': ['https://swapi.info/api/starships/48',
   'https://swapi.info/api/starships/59',
   'https://swapi.info/api/starships/64',
   'https://swapi.info/api/starships/65',
   'https://swapi.info/api/starships/74'],
  'created': '2014-12-10T16:16:29.192000Z',
  'edited': '2014-12-20T21:17:50.325000Z',
  'url': 'https://swapi.info/api/people/10'},
 {'name': 'Anakin Skywalker',
  'height': '188',
  'mass': '84',
  'hair_color': 'blond',
  'skin_color': 'fair',
  'eye_color': 'blue',
  'birth_year': '41.9BBY',
  'gender': 'male',
  'homeworld': 'https://swapi.info/api/planets/1',
  'films': ['https://swapi.info/api/films/4',
   'https://swapi.info/api/films/5',
   'https://swapi.info/api/films/6'],
  'species': [],
  'vehicles': ['https://swapi.info/api/vehicles/44',
   'https://swapi.info/api/vehicles/46'],
  'starships': ['https://swapi.info/api/starships/39',
   'https://swapi.info/api/starships/59',
   'https://swapi.info/api/starships/65'],
  'created': '2014-12-10T16:20:44.310000Z',
  'edited': '2014-12-20T21:17:50.327000Z',
  'url': 'https://swapi.info/api/people/11'},
 {'name': 'Wilhuff Tarkin',
  'height': '180',
  'mass': 'unknown',
  'hair_color': 'auburn, grey',
  'skin_color': 'fair',
  'eye_color': 'blue',
  'birth_year': '64BBY',
  'gender': 'male',
  'homeworld': 'https://swapi.info/api/planets/21',
  'films': ['https://swapi.info/api/films/1',
   'https://swapi.info/api/films/6'],
  'species': [],
  'vehicles': [],
  'starships': [],
  'created': '2014-12-10T16:26:56.138000Z',
  'edited': '2014-12-20T21:17:50.330000Z',
  'url': 'https://swapi.info/api/people/12'},
 {'name': 'Chewbacca',
  'height': '228',
  'mass': '112',
  'hair_color': 'brown',
  'skin_color': 'unknown',
  'eye_color': 'blue',
  'birth_year': '200BBY',
  'gender': 'male',
  'homeworld': 'https://swapi.info/api/planets/14',
  'films': ['https://swapi.info/api/films/1',
   'https://swapi.info/api/films/2',
   'https://swapi.info/api/films/3',
   'https://swapi.info/api/films/6'],
  'species': ['https://swapi.info/api/species/3'],
  'vehicles': ['https://swapi.info/api/vehicles/19'],
  'starships': ['https://swapi.info/api/starships/10',
   'https://swapi.info/api/starships/22'],
  'created': '2014-12-10T16:42:45.066000Z',
  'edited': '2014-12-20T21:17:50.332000Z',
  'url': 'https://swapi.info/api/people/13'},
 {'name': 'Han Solo',
  'height': '180',
  'mass': '80',
  'hair_color': 'brown',
  'skin_color': 'fair',
  'eye_color': 'brown',
  'birth_year': '29BBY',
  'gender': 'male',
  'homeworld': 'https://swapi.info/api/planets/22',
  'films': ['https://swapi.info/api/films/1',
   'https://swapi.info/api/films/2',
   'https://swapi.info/api/films/3'],
  'species': [],
  'vehicles': [],
  'starships': ['https://swapi.info/api/starships/10',
   'https://swapi.info/api/starships/22'],
  'created': '2014-12-10T16:49:14.582000Z',
  'edited': '2014-12-20T21:17:50.334000Z',
  'url': 'https://swapi.info/api/people/14'},
 {'name': 'Greedo',
  'height': '173',
  'mass': '74',
  'hair_color': 'n/a',
  'skin_color': 'green',
  'eye_color': 'black',
  'birth_year': '44BBY',
  'gender': 'male',
  'homeworld': 'https://swapi.info/api/planets/23',
  'films': ['https://swapi.info/api/films/1'],
  'species': ['https://swapi.info/api/species/4'],
  'vehicles': [],
  'starships': [],
  'created': '2014-12-10T17:03:30.334000Z',
  'edited': '2014-12-20T21:17:50.336000Z',
  'url': 'https://swapi.info/api/people/15'},
 {'name': 'Jabba Desilijic Tiure',
  'height': '175',
  'mass': '1,358',
  'hair_color': 'n/a',
  'skin_color': 'green-tan, brown',
  'eye_color': 'orange',
  'birth_year': '600BBY',
  'gender': 'hermaphrodite',
  'homeworld': 'https://swapi.info/api/planets/24',
  'films': ['https://swapi.info/api/films/1',
   'https://swapi.info/api/films/3',
   'https://swapi.info/api/films/4'],
  'species': ['https://swapi.info/api/species/5'],
  'vehicles': [],
  'starships': [],
  'created': '2014-12-10T17:11:31.638000Z',
  'edited': '2014-12-20T21:17:50.338000Z',
  'url': 'https://swapi.info/api/people/16'},
 {'name': 'Wedge Antilles',
  'height': '170',
  'mass': '77',
  'hair_color': 'brown',
  'skin_color': 'fair',
  'eye_color': 'hazel',
  'birth_year': '21BBY',
  'gender': 'male',
  'homeworld': 'https://swapi.info/api/planets/22',
  'films': ['https://swapi.info/api/films/1',
   'https://swapi.info/api/films/2',
   'https://swapi.info/api/films/3'],
  'species': [],
  'vehicles': ['https://swapi.info/api/vehicles/14'],
  'starships': ['https://swapi.info/api/starships/12'],
  'created': '2014-12-12T11:08:06.469000Z',
  'edited': '2014-12-20T21:17:50.341000Z',
  'url': 'https://swapi.info/api/people/18'},
 {'name': 'Jek Tono Porkins',
  'height': '180',
  'mass': '110',
  'hair_color': 'brown',
  'skin_color': 'fair',
  'eye_color': 'blue',
  'birth_year': 'unknown',
  'gender': 'male',
  'homeworld': 'https://swapi.info/api/planets/26',
  'films': ['https://swapi.info/api/films/1'],
  'species': [],
  'vehicles': [],
  'starships': ['https://swapi.info/api/starships/12'],
  'created': '2014-12-12T11:16:56.569000Z',
  'edited': '2014-12-20T21:17:50.343000Z',
  'url': 'https://swapi.info/api/people/19'},
 {'name': 'Yoda',
  'height': '66',
  'mass': '17',
  'hair_color': 'white',
  'skin_color': 'green',
  'eye_color': 'brown',
  'birth_year': '896BBY',
  'gender': 'male',
  'homeworld': 'https://swapi.info/api/planets/28',
  'films': ['https://swapi.info/api/films/2',
   'https://swapi.info/api/films/3',
   'https://swapi.info/api/films/4',
   'https://swapi.info/api/films/5',
   'https://swapi.info/api/films/6'],
  'species': ['https://swapi.info/api/species/6'],
  'vehicles': [],
  'starships': [],
  'created': '2014-12-15T12:26:01.042000Z',
  'edited': '2014-12-20T21:17:50.345000Z',
  'url': 'https://swapi.info/api/people/20'},
 {'name': 'Palpatine',
  'height': '170',
  'mass': '75',
  'hair_color': 'grey',
  'skin_color': 'pale',
  'eye_color': 'yellow',
  'birth_year': '82BBY',
  'gender': 'male',
  'homeworld': 'https://swapi.info/api/planets/8',
  'films': ['https://swapi.info/api/films/2',
   'https://swapi.info/api/films/3',
   'https://swapi.info/api/films/4',
   'https://swapi.info/api/films/5',
   'https://swapi.info/api/films/6'],
  'species': [],
  'vehicles': [],
  'starships': [],
  'created': '2014-12-15T12:48:05.971000Z',
  'edited': '2014-12-20T21:17:50.347000Z',
  'url': 'https://swapi.info/api/people/21'},
 {'name': 'Boba Fett',
  'height': '183',
  'mass': '78.2',
  'hair_color': 'black',
  'skin_color': 'fair',
  'eye_color': 'brown',
  'birth_year': '31.5BBY',
  'gender': 'male',
  'homeworld': 'https://swapi.info/api/planets/10',
  'films': ['https://swapi.info/api/films/2',
   'https://swapi.info/api/films/3',
   'https://swapi.info/api/films/5'],
  'species': [],
  'vehicles': [],
  'starships': ['https://swapi.info/api/starships/21'],
  'created': '2014-12-15T12:49:32.457000Z',
  'edited': '2014-12-20T21:17:50.349000Z',
  'url': 'https://swapi.info/api/people/22'},
 {'name': 'IG-88',
  'height': '200',
  'mass': '140',
  'hair_color': 'none',
  'skin_color': 'metal',
  'eye_color': 'red',
  'birth_year': '15BBY',
  'gender': 'none',
  'homeworld': 'https://swapi.info/api/planets/28',
  'films': ['https://swapi.info/api/films/2'],
  'species': ['https://swapi.info/api/species/2'],
  'vehicles': [],
  'starships': [],
  'created': '2014-12-15T12:51:10.076000Z',
  'edited': '2014-12-20T21:17:50.351000Z',
  'url': 'https://swapi.info/api/people/23'},
 {'name': 'Bossk',
  'height': '190',
  'mass': '113',
  'hair_color': 'none',
  'skin_color': 'green',
  'eye_color': 'red',
  'birth_year': '53BBY',
  'gender': 'male',
  'homeworld': 'https://swapi.info/api/planets/29',
  'films': ['https://swapi.info/api/films/2'],
  'species': ['https://swapi.info/api/species/7'],
  'vehicles': [],
  'starships': [],
  'created': '2014-12-15T12:53:49.297000Z',
  'edited': '2014-12-20T21:17:50.355000Z',
  'url': 'https://swapi.info/api/people/24'},
 {'name': 'Lando Calrissian',
  'height': '177',
  'mass': '79',
  'hair_color': 'black',
  'skin_color': 'dark',
  'eye_color': 'brown',
  'birth_year': '31BBY',
  'gender': 'male',
  'homeworld': 'https://swapi.info/api/planets/30',
  'films': ['https://swapi.info/api/films/2',
   'https://swapi.info/api/films/3'],
  'species': [],
  'vehicles': [],
  'starships': ['https://swapi.info/api/starships/10'],
  'created': '2014-12-15T12:56:32.683000Z',
  'edited': '2014-12-20T21:17:50.357000Z',
  'url': 'https://swapi.info/api/people/25'},
 {'name': 'Lobot',
  'height': '175',
  'mass': '79',
  'hair_color': 'none',
  'skin_color': 'light',
  'eye_color': 'blue',
  'birth_year': '37BBY',
  'gender': 'male',
  'homeworld': 'https://swapi.info/api/planets/6',
  'films': ['https://swapi.info/api/films/2'],
  'species': [],
  'vehicles': [],
  'starships': [],
  'created': '2014-12-15T13:01:57.178000Z',
  'edited': '2014-12-20T21:17:50.359000Z',
  'url': 'https://swapi.info/api/people/26'},
 {'name': 'Ackbar',
  'height': '180',
  'mass': '83',
  'hair_color': 'none',
  'skin_color': 'brown mottle',
  'eye_color': 'orange',
  'birth_year': '41BBY',
  'gender': 'male',
  'homeworld': 'https://swapi.info/api/planets/31',
  'films': ['https://swapi.info/api/films/3'],
  'species': ['https://swapi.info/api/species/8'],
  'vehicles': [],
  'starships': [],
  'created': '2014-12-18T11:07:50.584000Z',
  'edited': '2014-12-20T21:17:50.362000Z',
  'url': 'https://swapi.info/api/people/27'},
 {'name': 'Mon Mothma',
  'height': '150',
  'mass': 'unknown',
  'hair_color': 'auburn',
  'skin_color': 'fair',
  'eye_color': 'blue',
  'birth_year': '48BBY',
  'gender': 'female',
  'homeworld': 'https://swapi.info/api/planets/32',
  'films': ['https://swapi.info/api/films/3'],
  'species': [],
  'vehicles': [],
  'starships': [],
  'created': '2014-12-18T11:12:38.895000Z',
  'edited': '2014-12-20T21:17:50.364000Z',
  'url': 'https://swapi.info/api/people/28'},
 {'name': 'Arvel Crynyd',
  'height': 'unknown',
  'mass': 'unknown',
  'hair_color': 'brown',
  'skin_color': 'fair',
  'eye_color': 'brown',
  'birth_year': 'unknown',
  'gender': 'male',
  'homeworld': 'https://swapi.info/api/planets/28',
  'films': ['https://swapi.info/api/films/3'],
  'species': [],
  'vehicles': [],
  'starships': ['https://swapi.info/api/starships/28'],
  'created': '2014-12-18T11:16:33.020000Z',
  'edited': '2014-12-20T21:17:50.367000Z',
  'url': 'https://swapi.info/api/people/29'},
 {'name': 'Wicket Systri Warrick',
  'height': '88',
  'mass': '20',
  'hair_color': 'brown',
  'skin_color': 'brown',
  'eye_color': 'brown',
  'birth_year': '8BBY',
  'gender': 'male',
  'homeworld': 'https://swapi.info/api/planets/7',
  'films': ['https://swapi.info/api/films/3'],
  'species': ['https://swapi.info/api/species/9'],
  'vehicles': [],
  'starships': [],
  'created': '2014-12-18T11:21:58.954000Z',
  'edited': '2014-12-20T21:17:50.369000Z',
  'url': 'https://swapi.info/api/people/30'},
 {'name': 'Nien Nunb',
  'height': '160',
  'mass': '68',
  'hair_color': 'none',
  'skin_color': 'grey',
  'eye_color': 'black',
  'birth_year': 'unknown',
  'gender': 'male',
  'homeworld': 'https://swapi.info/api/planets/33',
  'films': ['https://swapi.info/api/films/3'],
  'species': ['https://swapi.info/api/species/10'],
  'vehicles': [],
  'starships': ['https://swapi.info/api/starships/10'],
  'created': '2014-12-18T11:26:18.541000Z',
  'edited': '2014-12-20T21:17:50.371000Z',
  'url': 'https://swapi.info/api/people/31'},
 {'name': 'Qui-Gon Jinn',
  'height': '193',
  'mass': '89',
  'hair_color': 'brown',
  'skin_color': 'fair',
  'eye_color': 'blue',
  'birth_year': '92BBY',
  'gender': 'male',
  'homeworld': 'https://swapi.info/api/planets/28',
  'films': ['https://swapi.info/api/films/4'],
  'species': [],
  'vehicles': ['https://swapi.info/api/vehicles/38'],
  'starships': [],
  'created': '2014-12-19T16:54:53.618000Z',
  'edited': '2014-12-20T21:17:50.375000Z',
  'url': 'https://swapi.info/api/people/32'},
 {'name': 'Nute Gunray',
  'height': '191',
  'mass': '90',
  'hair_color': 'none',
  'skin_color': 'mottled green',
  'eye_color': 'red',
  'birth_year': 'unknown',
  'gender': 'male',
  'homeworld': 'https://swapi.info/api/planets/18',
  'films': ['https://swapi.info/api/films/4',
   'https://swapi.info/api/films/5',
   'https://swapi.info/api/films/6'],
  'species': ['https://swapi.info/api/species/11'],
  'vehicles': [],
  'starships': [],
  'created': '2014-12-19T17:05:57.357000Z',
  'edited': '2014-12-20T21:17:50.377000Z',
  'url': 'https://swapi.info/api/people/33'},
 {'name': 'Finis Valorum',
  'height': '170',
  'mass': 'unknown',
  'hair_color': 'blond',
  'skin_color': 'fair',
  'eye_color': 'blue',
  'birth_year': '91BBY',
  'gender': 'male',
  'homeworld': 'https://swapi.info/api/planets/9',
  'films': ['https://swapi.info/api/films/4'],
  'species': [],
  'vehicles': [],
  'starships': [],
  'created': '2014-12-19T17:21:45.915000Z',
  'edited': '2014-12-20T21:17:50.379000Z',
  'url': 'https://swapi.info/api/people/34'},
 {'name': 'Padmé Amidala',
  'height': '185',
  'mass': '45',
  'hair_color': 'brown',
  'skin_color': 'light',
  'eye_color': 'brown',
  'birth_year': '46BBY',
  'gender': 'female',
  'homeworld': 'https://swapi.info/api/planets/8',
  'films': ['https://swapi.info/api/films/4',
   'https://swapi.info/api/films/5',
   'https://swapi.info/api/films/6'],
  'species': [],
  'vehicles': [],
  'starships': ['https://swapi.info/api/starships/39',
   'https://swapi.info/api/starships/49',
   'https://swapi.info/api/starships/64'],
  'created': '2014-12-19T17:28:26.926000Z',
  'edited': '2014-12-20T21:17:50.381000Z',
  'url': 'https://swapi.info/api/people/35'},
 {'name': 'Jar Jar Binks',
  'height': '196',
  'mass': '66',
  'hair_color': 'none',
  'skin_color': 'orange',
  'eye_color': 'orange',
  'birth_year': '52BBY',
  'gender': 'male',
  'homeworld': 'https://swapi.info/api/planets/8',
  'films': ['https://swapi.info/api/films/4',
   'https://swapi.info/api/films/5'],

In [14]:
data=[]
data.append(response_json)
data

[[{'name': 'Luke Skywalker',
   'height': '172',
   'mass': '77',
   'hair_color': 'blond',
   'skin_color': 'fair',
   'eye_color': 'blue',
   'birth_year': '19BBY',
   'gender': 'male',
   'homeworld': 'https://swapi.info/api/planets/1',
   'films': ['https://swapi.info/api/films/1',
    'https://swapi.info/api/films/2',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/6'],
   'species': [],
   'vehicles': ['https://swapi.info/api/vehicles/14',
    'https://swapi.info/api/vehicles/30'],
   'starships': ['https://swapi.info/api/starships/12',
    'https://swapi.info/api/starships/22'],
   'created': '2014-12-09T13:50:51.644000Z',
   'edited': '2014-12-20T21:17:56.891000Z',
   'url': 'https://swapi.info/api/people/1'},
  {'name': 'C-3PO',
   'height': '167',
   'mass': '75',
   'hair_color': 'n/a',
   'skin_color': 'gold',
   'eye_color': 'yellow',
   'birth_year': '112BBY',
   'gender': 'n/a',
   'homeworld': 'https://swapi.info/api/planets/1',
   'films': ['https://swapi.info/api/films/1',
    'https://swapi.info/api/films/2',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/4',
    'https://swapi.info/api/films/5',
    'https://swapi.info/api/films/6'],
   'species': ['https://swapi.info/api/species/2'],
   'vehicles': [],
   'starships': [],
   'created': '2014-12-10T15:10:51.357000Z',
   'edited': '2014-12-20T21:17:50.309000Z',
   'url': 'https://swapi.info/api/people/2'},
  {'name': 'R2-D2',
   'height': '96',
   'mass': '32',
   'hair_color': 'n/a',
   'skin_color': 'white, blue',
   'eye_color': 'red',
   'birth_year': '33BBY',
   'gender': 'n/a',
   'homeworld': 'https://swapi.info/api/planets/8',
   'films': ['https://swapi.info/api/films/1',
    'https://swapi.info/api/films/2',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/4',
    'https://swapi.info/api/films/5',
    'https://swapi.info/api/films/6'],
   'species': ['https://swapi.info/api/species/2'],
   'vehicles': [],
   'starships': [],
   'created': '2014-12-10T15:11:50.376000Z',
   'edited': '2014-12-20T21:17:50.311000Z',
   'url': 'https://swapi.info/api/people/3'},
  {'name': 'Darth Vader',
   'height': '202',
   'mass': '136',
   'hair_color': 'none',
   'skin_color': 'white',
   'eye_color': 'yellow',
   'birth_year': '41.9BBY',
   'gender': 'male',
   'homeworld': 'https://swapi.info/api/planets/1',
   'films': ['https://swapi.info/api/films/1',
    'https://swapi.info/api/films/2',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/6'],
   'species': [],
   'vehicles': [],
   'starships': ['https://swapi.info/api/starships/13'],
   'created': '2014-12-10T15:18:20.704000Z',
   'edited': '2014-12-20T21:17:50.313000Z',
   'url': 'https://swapi.info/api/people/4'},
  {'name': 'Leia Organa',
   'height': '150',
   'mass': '49',
   'hair_color': 'brown',
   'skin_color': 'light',
   'eye_color': 'brown',
   'birth_year': '19BBY',
   'gender': 'female',
   'homeworld': 'https://swapi.info/api/planets/2',
   'films': ['https://swapi.info/api/films/1',
    'https://swapi.info/api/films/2',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/6'],
   'species': [],
   'vehicles': ['https://swapi.info/api/vehicles/30'],
   'starships': [],
   'created': '2014-12-10T15:20:09.791000Z',
   'edited': '2014-12-20T21:17:50.315000Z',
   'url': 'https://swapi.info/api/people/5'},
  {'name': 'Owen Lars',
   'height': '178',
   'mass': '120',
   'hair_color': 'brown, grey',
   'skin_color': 'light',
   'eye_color': 'blue',
   'birth_year': '52BBY',
   'gender': 'male',
   'homeworld': 'https://swapi.info/api/planets/1',
   'films': ['https://swapi.info/api/films/1',
    'https://swapi.info/api/films/5',
    'https://swapi.info/api/films/6'],
   'species': [],
   'vehicles': [],
   'starships': [],
   'created': '2014-12-10T15:52:14.024000Z',
   'edited': '2014-12-20T21:17:50.317000Z',
   'url': 'https://swapi.info/api/people/6'},
  {'name': 'Beru Whitesun lars',
   'height': '165',
   'mass': '75',
   'hair_color': 'brown',
   'skin_color': 'light',
   'eye_color': 'blue',
   'birth_year': '47BBY',
   'gender': 'female',
   'homeworld': 'https://swapi.info/api/planets/1',
   'films': ['https://swapi.info/api/films/1',
    'https://swapi.info/api/films/5',
    'https://swapi.info/api/films/6'],
   'species': [],
   'vehicles': [],
   'starships': [],
   'created': '2014-12-10T15:53:41.121000Z',
   'edited': '2014-12-20T21:17:50.319000Z',
   'url': 'https://swapi.info/api/people/7'},
  {'name': 'R5-D4',
   'height': '97',
   'mass': '32',
   'hair_color': 'n/a',
   'skin_color': 'white, red',
   'eye_color': 'red',
   'birth_year': 'unknown',
   'gender': 'n/a',
   'homeworld': 'https://swapi.info/api/planets/1',
   'films': ['https://swapi.info/api/films/1'],
   'species': ['https://swapi.info/api/species/2'],
   'vehicles': [],
   'starships': [],
   'created': '2014-12-10T15:57:50.959000Z',
   'edited': '2014-12-20T21:17:50.321000Z',
   'url': 'https://swapi.info/api/people/8'},
  {'name': 'Biggs Darklighter',
   'height': '183',
   'mass': '84',
   'hair_color': 'black',
   'skin_color': 'light',
   'eye_color': 'brown',
   'birth_year': '24BBY',
   'gender': 'male',
   'homeworld': 'https://swapi.info/api/planets/1',
   'films': ['https://swapi.info/api/films/1'],
   'species': [],
   'vehicles': [],
   'starships': ['https://swapi.info/api/starships/12'],
   'created': '2014-12-10T15:59:50.509000Z',
   'edited': '2014-12-20T21:17:50.323000Z',
   'url': 'https://swapi.info/api/people/9'},
  {'name': 'Obi-Wan Kenobi',
   'height': '182',
   'mass': '77',
   'hair_color': 'auburn, white',
   'skin_color': 'fair',
   'eye_color': 'blue-gray',
   'birth_year': '57BBY',
   'gender': 'male',
   'homeworld': 'https://swapi.info/api/planets/20',
   'films': ['https://swapi.info/api/films/1',
    'https://swapi.info/api/films/2',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/4',
    'https://swapi.info/api/films/5',
    'https://swapi.info/api/films/6'],
   'species': [],
   'vehicles': ['https://swapi.info/api/vehicles/38'],
   'starships': ['https://swapi.info/api/starships/48',
    'https://swapi.info/api/starships/59',
    'https://swapi.info/api/starships/64',
    'https://swapi.info/api/starships/65',
    'https://swapi.info/api/starships/74'],
   'created': '2014-12-10T16:16:29.192000Z',
   'edited': '2014-12-20T21:17:50.325000Z',
   'url': 'https://swapi.info/api/people/10'},
  {'name': 'Anakin Skywalker',
   'height': '188',
   'mass': '84',
   'hair_color': 'blond',
   'skin_color': 'fair',
   'eye_color': 'blue',
   'birth_year': '41.9BBY',
   'gender': 'male',
   'homeworld': 'https://swapi.info/api/planets/1',
   'films': ['https://swapi.info/api/films/4',
    'https://swapi.info/api/films/5',
    'https://swapi.info/api/films/6'],
   'species': [],
   'vehicles': ['https://swapi.info/api/vehicles/44',
    'https://swapi.info/api/vehicles/46'],
   'starships': ['https://swapi.info/api/starships/39',
    'https://swapi.info/api/starships/59',
    'https://swapi.info/api/starships/65'],
   'created': '2014-12-10T16:20:44.310000Z',
   'edited': '2014-12-20T21:17:50.327000Z',
   'url': 'https://swapi.info/api/people/11'},
  {'name': 'Wilhuff Tarkin',
   'height': '180',
   'mass': 'unknown',
   'hair_color': 'auburn, grey',
   'skin_color': 'fair',
   'eye_color': 'blue',
   'birth_year': '64BBY',
   'gender': 'male',
   'homeworld': 'https://swapi.info/api/planets/21',
   'films': ['https://swapi.info/api/films/1',
    'https://swapi.info/api/films/6'],
   'species': [],
   'vehicles': [],
   'starships': [],
   'created': '2014-12-10T16:26:56.138000Z',
   'edited': '2014-12-20T21:17:50.330000Z',
   'url': 'https://swapi.info/api/people/12'},
  {'name': 'Chewbacca',
   'height': '228',
   'mass': '112',
   'hair_color': 'brown',
   'skin_color': 'unknown',
   'eye_color': 'blue',
   'birth_year': '200BBY',
   'gender': 'male',
   'homeworld': 'https://swapi.info/api/planets/14',
   'films': ['https://swapi.info/api/films/1',
    'https://swapi.info/api/films/2',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/6'],
   'species': ['https://swapi.info/api/species/3'],
   'vehicles': ['https://swapi.info/api/vehicles/19'],
   'starships': ['https://swapi.info/api/starships/10',
    'https://swapi.info/api/starships/22'],
   'created': '2014-12-10T16:42:45.066000Z',
   'edited': '2014-12-20T21:17:50.332000Z',
   'url': 'https://swapi.info/api/people/13'},
  {'name': 'Han Solo',
   'height': '180',
   'mass': '80',
   'hair_color': 'brown',
   'skin_color': 'fair',
   'eye_color': 'brown',
   'birth_year': '29BBY',
   'gender': 'male',
   'homeworld': 'https://swapi.info/api/planets/22',
   'films': ['https://swapi.info/api/films/1',
    'https://swapi.info/api/films/2',
    'https://swapi.info/api/films/3'],
   'species': [],
   'vehicles': [],
   'starships': ['https://swapi.info/api/starships/10',
    'https://swapi.info/api/starships/22'],
   'created': '2014-12-10T16:49:14.582000Z',
   'edited': '2014-12-20T21:17:50.334000Z',
   'url': 'https://swapi.info/api/people/14'},
  {'name': 'Greedo',
   'height': '173',
   'mass': '74',
   'hair_color': 'n/a',
   'skin_color': 'green',
   'eye_color': 'black',
   'birth_year': '44BBY',
   'gender': 'male',
   'homeworld': 'https://swapi.info/api/planets/23',
   'films': ['https://swapi.info/api/films/1'],
   'species': ['https://swapi.info/api/species/4'],
   'vehicles': [],
   'starships': [],
   'created': '2014-12-10T17:03:30.334000Z',
   'edited': '2014-12-20T21:17:50.336000Z',
   'url': 'https://swapi.info/api/people/15'},
  {'name': 'Jabba Desilijic Tiure',
   'height': '175',
   'mass': '1,358',
   'hair_color': 'n/a',
   'skin_color': 'green-tan, brown',
   'eye_color': 'orange',
   'birth_year': '600BBY',
   'gender': 'hermaphrodite',
   'homeworld': 'https://swapi.info/api/planets/24',
   'films': ['https://swapi.info/api/films/1',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/4'],
   'species': ['https://swapi.info/api/species/5'],
   'vehicles': [],
   'starships': [],
   'created': '2014-12-10T17:11:31.638000Z',
   'edited': '2014-12-20T21:17:50.338000Z',
   'url': 'https://swapi.info/api/people/16'},
  {'name': 'Wedge Antilles',
   'height': '170',
   'mass': '77',
   'hair_color': 'brown',
   'skin_color': 'fair',
   'eye_color': 'hazel',
   'birth_year': '21BBY',
   'gender': 'male',
   'homeworld': 'https://swapi.info/api/planets/22',
   'films': ['https://swapi.info/api/films/1',
    'https://swapi.info/api/films/2',
    'https://swapi.info/api/films/3'],
   'species': [],
   'vehicles': ['https://swapi.info/api/vehicles/14'],
   'starships': ['https://swapi.info/api/starships/12'],
   'created': '2014-12-12T11:08:06.469000Z',
   'edited': '2014-12-20T21:17:50.341000Z',
   'url': 'https://swapi.info/api/people/18'},
  {'name': 'Jek Tono Porkins',
   'height': '180',
   'mass': '110',
   'hair_color': 'brown',
   'skin_color': 'fair',
   'eye_color': 'blue',
   'birth_year': 'unknown',
   'gender': 'male',
   'homeworld': 'https://swapi.info/api/planets/26',
   'films': ['https://swapi.info/api/films/1'],
   'species': [],
   'vehicles': [],
   'starships': ['https://swapi.info/api/starships/12'],
   'created': '2014-12-12T11:16:56.569000Z',
   'edited': '2014-12-20T21:17:50.343000Z',
   'url': 'https://swapi.info/api/people/19'},
  {'name': 'Yoda',
   'height': '66',
   'mass': '17',
   'hair_color': 'white',
   'skin_color': 'green',
   'eye_color': 'brown',
   'birth_year': '896BBY',
   'gender': 'male',
   'homeworld': 'https://swapi.info/api/planets/28',
   'films': ['https://swapi.info/api/films/2',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/4',
    'https://swapi.info/api/films/5',
    'https://swapi.info/api/films/6'],
   'species': ['https://swapi.info/api/species/6'],
   'vehicles': [],
   'starships': [],
   'created': '2014-12-15T12:26:01.042000Z',
   'edited': '2014-12-20T21:17:50.345000Z',
   'url': 'https://swapi.info/api/people/20'},
  {'name': 'Palpatine',
   'height': '170',
   'mass': '75',
   'hair_color': 'grey',
   'skin_color': 'pale',
   'eye_color': 'yellow',
   'birth_year': '82BBY',
   'gender': 'male',
   'homeworld': 'https://swapi.info/api/planets/8',
   'films': ['https://swapi.info/api/films/2',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/4',
    'https://swapi.info/api/films/5',
    'https://swapi.info/api/films/6'],
   'species': [],
   'vehicles': [],
   'starships': [],
   'created': '2014-12-15T12:48:05.971000Z',
   'edited': '2014-12-20T21:17:50.347000Z',
   'url': 'https://swapi.info/api/people/21'},
  {'name': 'Boba Fett',
   'height': '183',
   'mass': '78.2',
   'hair_color': 'black',
   'skin_color': 'fair',
   'eye_color': 'brown',
   'birth_year': '31.5BBY',
   'gender': 'male',
   'homeworld': 'https://swapi.info/api/planets/10',
   'films': ['https://swapi.info/api/films/2',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/5'],
   'species': [],
   'vehicles': [],
   'starships': ['https://swapi.info/api/starships/21'],
   'created': '2014-12-15T12:49:32.457000Z',
   'edited': '2014-12-20T21:17:50.349000Z',
   'url': 'https://swapi.info/api/people/22'},
  {'name': 'IG-88',
   'height': '200',
   'mass': '140',
   'hair_color': 'none',
   'skin_color': 'metal',
   'eye_color': 'red',
   'birth_year': '15BBY',
   'gender': 'none',
   'homeworld': 'https://swapi.info/api/planets/28',
   'films': ['https://swapi.info/api/films/2'],
   'species': ['https://swapi.info/api/species/2'],
   'vehicles': [],
   'starships': [],
   'created': '2014-12-15T12:51:10.076000Z',
   'edited': '2014-12-20T21:17:50.351000Z',
   'url': 'https://swapi.info/api/people/23'},
  {'name': 'Bossk',
   'height': '190',
   'mass': '113',
   'hair_color': 'none',
   'skin_color': 'green',
   'eye_color': 'red',
   'birth_year': '53BBY',
   'gender': 'male',
   'homeworld': 'https://swapi.info/api/planets/29',
   'films': ['https://swapi.info/api/films/2'],
   'species': ['https://swapi.info/api/species/7'],
   'vehicles': [],
   'starships': [],
   'created': '2014-12-15T12:53:49.297000Z',
   'edited': '2014-12-20T21:17:50.355000Z',
   'url': 'https://swapi.info/api/people/24'},
  {'name': 'Lando Calrissian',
   'height': '177',
   'mass': '79',
   'hair_color': 'black',
   'skin_color': 'dark',
   'eye_color': 'brown',
   'birth_year': '31BBY',
   'gender': 'male',
   'homeworld': 'https://swapi.info/api/planets/30',
   'films': ['https://swapi.info/api/films/2',
    'https://swapi.info/api/films/3'],
   'species': [],
   'vehicles': [],
   'starships': ['https://swapi.info/api/starships/10'],
   'created': '2014-12-15T12:56:32.683000Z',
   'edited': '2014-12-20T21:17:50.357000Z',
   'url': 'https://swapi.info/api/people/25'},
  {'name': 'Lobot',
   'height': '175',
   'mass': '79',
   'hair_color': 'none',
   'skin_color': 'light',
   'eye_color': 'blue',
   'birth_year': '37BBY',
   'gender': 'male',
   'homeworld': 'https://swapi.info/api/planets/6',
   'films': ['https://swapi.info/api/films/2'],
   'species': [],
   'vehicles': [],
   'starships': [],
   'created': '2014-12-15T13:01:57.178000Z',
   'edited': '2014-12-20T21:17:50.359000Z',
   'url': 'https://swapi.info/api/people/26'},
  {'name': 'Ackbar',
   'height': '180',
   'mass': '83',
   'hair_color': 'none',
   'skin_color': 'brown mottle',
   'eye_color': 'orange',
   'birth_year': '41BBY',
   'gender': 'male',
   'homeworld': 'https://swapi.info/api/planets/31',
   'films': ['https://swapi.info/api/films/3'],
   'species': ['https://swapi.info/api/species/8'],
   'vehicles': [],
   'starships': [],
   'created': '2014-12-18T11:07:50.584000Z',
   'edited': '2014-12-20T21:17:50.362000Z',
   'url': 'https://swapi.info/api/people/27'},
  {'name': 'Mon Mothma',
   'height': '150',
   'mass': 'unknown',
   'hair_color': 'auburn',
   'skin_color': 'fair',
   'eye_color': 'blue',
   'birth_year': '48BBY',
   'gender': 'female',
   'homeworld': 'https://swapi.info/api/planets/32',
   'films': ['https://swapi.info/api/films/3'],
   'species': [],
   'vehicles': [],
   'starships': [],
   'created': '2014-12-18T11:12:38.895000Z',
   'edited': '2014-12-20T21:17:50.364000Z',
   'url': 'https://swapi.info/api/people/28'},
  {'name': 'Arvel Crynyd',
   'height': 'unknown',
   'mass': 'unknown',
   'hair_color': 'brown',
   'skin_color': 'fair',
   'eye_color': 'brown',
   'birth_year': 'unknown',
   'gender': 'male',
   'homeworld': 'https://swapi.info/api/planets/28',
   'films': ['https://swapi.info/api/films/3'],
   'species': [],
   'vehicles': [],
   'starships': ['https://swapi.info/api/starships/28'],
   'created': '2014-12-18T11:16:33.020000Z',
   'edited': '2014-12-20T21:17:50.367000Z',
   'url': 'https://swapi.info/api/people/29'},
  {'name': 'Wicket Systri Warrick',
   'height': '88',
   'mass': '20',
   'hair_color': 'brown',
   'skin_color': 'brown',
   'eye_color': 'brown',
   'birth_year': '8BBY',
   'gender': 'male',
   'homeworld': 'https://swapi.info/api/planets/7',
   'films': ['https://swapi.info/api/films/3'],
   'species': ['https://swapi.info/api/species/9'],
   'vehicles': [],
   'starships': [],
   'created': '2014-12-18T11:21:58.954000Z',
   'edited': '2014-12-20T21:17:50.369000Z',
   'url': 'https://swapi.info/api/people/30'},
  {'name': 'Nien Nunb',
   'height': '160',
   'mass': '68',
   'hair_color': 'none',
   'skin_color': 'grey',
   'eye_color': 'black',
   'birth_year': 'unknown',
   'gender': 'male',
   'homeworld': 'https://swapi.info/api/planets/33',
   'films': ['https://swapi.info/api/films/3'],
   'species': ['https://swapi.info/api/species/10'],
   'vehicles': [],
   'starships': ['https://swapi.info/api/starships/10'],
   'created': '2014-12-18T11:26:18.541000Z',
   'edited': '2014-12-20T21:17:50.371000Z',
   'url': 'https://swapi.info/api/people/31'},
  {'name': 'Qui-Gon Jinn',
   'height': '193',
   'mass': '89',
   'hair_color': 'brown',
   'skin_color': 'fair',
   'eye_color': 'blue',
   'birth_year': '92BBY',
   'gender': 'male',
   'homeworld': 'https://swapi.info/api/planets/28',
   'films': ['https://swapi.info/api/films/4'],
   'species': [],
   'vehicles': ['https://swapi.info/api/vehicles/38'],
   'starships': [],
   'created': '2014-12-19T16:54:53.618000Z',
   'edited': '2014-12-20T21:17:50.375000Z',
   'url': 'https://swapi.info/api/people/32'},
  {'name': 'Nute Gunray',
   'height': '191',
   'mass': '90',
   'hair_color': 'none',
   'skin_color': 'mottled green',
   'eye_color': 'red',
   'birth_year': 'unknown',
   'gender': 'male',
   'homeworld': 'https://swapi.info/api/planets/18',
   'films': ['https://swapi.info/api/films/4',
    'https://swapi.info/api/films/5',
    'https://swapi.info/api/films/6'],
   'species': ['https://swapi.info/api/species/11'],
   'vehicles': [],
   'starships': [],
   'created': '2014-12-19T17:05:57.357000Z',
   'edited': '2014-12-20T21:17:50.377000Z',
   'url': 'https://swapi.info/api/people/33'},
  {'name': 'Finis Valorum',
   'height': '170',
   'mass': 'unknown',
   'hair_color': 'blond',
   'skin_color': 'fair',
   'eye_color': 'blue',
   'birth_year': '91BBY',
   'gender': 'male',
   'homeworld': 'https://swapi.info/api/planets/9',
   'films': ['https://swapi.info/api/films/4'],
   'species': [],
   'vehicles': [],
   'starships': [],
   'created': '2014-12-19T17:21:45.915000Z',
   'edited': '2014-12-20T21:17:50.379000Z',
   'url': 'https://swapi.info/api/people/34'},
  {'name': 'Padmé Amidala',
   'height': '185',
   'mass': '45',
   'hair_color': 'brown',
   'skin_color': 'light',
   'eye_color': 'brown',
   'birth_year': '46BBY',
   'gender': 'female',
   'homeworld': 'https://swapi.info/api/planets/8',
   'films': ['https://swapi.info/api/films/4',
    'https://swapi.info/api/films/5',
    'https://swapi.info/api/films/6'],
   'species': [],
   'vehicles': [],

In [62]:
##for loop : get data from api for person 1 to 10
import time

name=[]
for i in range(10):
    url=f"https://swapi.info/api/people/{i+1}"
    response=requests.get(url)
    response_json=response.json()
    name.append(response_json["name"])
    print(f"sucess character :{i+1}")
    time.sleep(1)

print(name)

sucess character :1
sucess character :2
sucess character :3
sucess character :4
sucess character :5
sucess character :6
sucess character :7
sucess character :8
sucess character :9
sucess character :10
['Luke Skywalker', 'C-3PO', 'R2-D2', 'Darth Vader', 'Leia Organa', 'Owen Lars', 'Beru Whitesun lars', 'R5-D4', 'Biggs Darklighter', 'Obi-Wan Kenobi']

In [5]:
##for loop : get data from api for person 1 to 10
import time

characters=[]
for i in range(10):
    url=f"https://swapi.info/api/people/{i+1}"
    response=requests.get(url)
    response_json=response.json()
    data=[response_json["name"],
          response_json["height"],
          response_json["mass"]]
    characters.append(data)
    print(f"sucess character :{i+1}")
    time.sleep(1)

print(characters)

sucess character :1
sucess character :2
sucess character :3
sucess character :4
sucess character :5
sucess character :6
sucess character :7
sucess character :8
sucess character :9
sucess character :10
[['Luke Skywalker', '172', '77'], ['C-3PO', '167', '75'], ['R2-D2', '96', '32'], ['Darth Vader', '202', '136'], ['Leia Organa', '150', '49'], ['Owen Lars', '178', '120'], ['Beru Whitesun lars', '165', '75'], ['R5-D4', '97', '32'], ['Biggs Darklighter', '183', '84'], ['Obi-Wan Kenobi', '182', '77']]

In [6]:
characters

[['Luke Skywalker', '172', '77'],
 ['C-3PO', '167', '75'],
 ['R2-D2', '96', '32'],
 ['Darth Vader', '202', '136'],
 ['Leia Organa', '150', '49'],
 ['Owen Lars', '178', '120'],
 ['Beru Whitesun lars', '165', '75'],
 ['R5-D4', '97', '32'],
 ['Biggs Darklighter', '183', '84'],
 ['Obi-Wan Kenobi', '182', '77']]

In [64]:
starwars=pd.DataFrame(characters,columns =["name","height","mass"])
starwars

                 name height mass
0      Luke Skywalker    172   77
1               C-3PO    167   75
2               R2-D2     96   32
3         Darth Vader    202  136
4         Leia Organa    150   49
5           Owen Lars    178  120
6  Beru Whitesun lars    165   75
7               R5-D4     97   32
8   Biggs Darklighter    183   84
9      Obi-Wan Kenobi    182   77